### ISSUE TITLE
help error. once you click launch error 

### ISSUE THREAD

**Issue by kwaknet01** [JMoore96/EnglishToGermanTranslator#1]
> node server.js

Running at Port 8080
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn py ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1

i use windows 10.
ive already installed all nessecary files needed.. checked deep_version.py, versions.py..

**Comment by kwaknet01** [comment]
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle WarayTagalogTranslator@1.0.0~prestart: WarayTagalogTranslator@1.0.0
6 info lifecycle WarayTagalogTranslator@1.0.0~start: WarayTagalogTranslator@1.0.0
7 verbose lifecycle WarayTagalogTranslator@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle WarayTagalogTranslator@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Maquinano\Anaconda3\WarayTagalogTranslator\node_modules\.bin;C:\Users\Maquinano\Anaconda3;C:\Users\Maquinano\Anaconda3\Library\mingw-w64\bin;C:\Users\Maquinano\Anaconda3\Library\usr\bin;C:\Users\Maquinano\Anaconda3\Library\bin;C:\Users\Maquinano\Anaconda3\Scripts;C:\Users\Maquinano\Anaconda3\bin;C:\Users\Maquinano\Anaconda3\condabin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\Java\jdk1.8.0_161\bin;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;E:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\program files (x86)\microsoft visual studio 14.0\vc\bin;C:\Program Files\nodejs;C:\Program Files (x86)\nodejs\npm;C:\Program Files (x86)\nodejs\npm.cmd;C:\Program Files (x86)\Java\jdk1.8.0_161\bin;C:\Users\Maquinano\AppData\Roaming\Composer\vendor\bin;C:\program files (x86)\microsoft visual studio 14.0\vc\bin;C:\Users\Maquinano\AppData\Roaming\npm;C:\Program Files (x86)\nodejs\npm;C:\Program Files (x86)\nodejs\npm.cmd;.
9 verbose lifecycle WarayTagalogTranslator@1.0.0~start: CWD: C:\Users\Maquinano\Anaconda3\WarayTagalogTranslator
10 silly lifecycle WarayTagalogTranslator@1.0.0~start: Args: [ '/d /s /c', 'node server.js' ]
11 silly lifecycle WarayTagalogTranslator@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle WarayTagalogTranslator@1.0.0~start: Failed to exec start script
13 verbose stack Error: WarayTagalogTranslator@1.0.0 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid WarayTagalogTranslator@1.0.0
15 verbose cwd C:\Users\Maquinano\Anaconda3\WarayTagalogTranslator
16 verbose Windows_NT 10.0.17758
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error WarayTagalogTranslator@1.0.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the WarayTagalogTranslator@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by kwaknet01** [comment]
adding python path to the options will solve the problem..

FOR WINDOWS;
`    var options = {`
   `     mode: 'text',`
	`	pythonPath: "add your python path here ex. "C:\\User\\Anaconda3\\python.exe",`
	`	pythonOptions: ['-u'], // get print results in real-time`
     `   args: [epochVal, reverseVal]`
`    };`

**SOLVE ISSUE**
